### ISSUE TITLE
az-availability-set role is using an incorrect fault_domain default

### ISSUE THREAD

**Issue by dumblerod** [rdvansloten/az-availability-set#1]
When using the az-availability-set role, I get the error below:

Error creating the availability set: Azure Error: InvalidParameter\nMessage: The specified fault domain count 3 must fall in the range 1 to 2.\nTarget: platformFaultDomainCount

avset_fault_domains should default to 2 instead.

**Comment by rdvansloten** [comment]
@dumblerod Hi, I think this is a region-specific setting that varies per region. I'm successfully deploying it in westeurope, could you let me know which region you're deploying to? I would like to reproduce the issue!

**Comment by dumblerod** [comment]
I thought that might be the case after I submitted.  I ran in westus2.

________________________________

**Comment by rdvansloten** [comment]
At a bit of a crossroads here as to what to do. Highly available clusters such as Galera XtraDB, Microsoft Failover Clustering, Redis (with Sentinel), MS SQL AlwaysOn dictate that there should be 3 VMs at minimum (namely, 2 main instances and an arbiter/witness or simply 3 main instances) so a default of 2 would deviate from that standard. On the other hand, a default should "just work." What do you think?

**Comment by dumblerod** [comment]
I was doing a little research to find out if there was a way to retrieve this value and couldn't find a programmatic way.  I did find this link: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/manage-availability#use-managed-disks-for-vms-in-an-availability-set which if you scroll down a little past that header will show that the majority of regions only allow 2.  Even with 2 fault domain, you wouldn't be limited in deploying a 3 VM cluster and you could override if you REALLY wanted to put each VM in it's own fault domain.  Thanks by the way for putting all these together.  They're really good!

**Comment by rdvansloten** [comment]
Haha, I had the same page open at this point. I'll change the default to 2, but that does technically mean 2/3 VMs could be unavailable in the default config, unless you start using availability zones or multiple sets, I believe. The diagram they attached with the 3 racks would imply this.

And thanks! Still a work in progress. currently working on the VM scaleset + load balancer and the results are promising so far. If you have any suggestions or improvements, let me know!
